In [3]:
import numpy as np
import random

horizontal = [2, 1, -1, -2, -2, -1, 1, 2]
vertical = [-1, -2, -2, -1, 1, 2, 2, 1]

def is_valid_move(row, col, board):
    return 0 <= row < 8 and 0 <= col < 8 and board[row, col] == 0

def random_knights_tour():
    board = np.zeros((8, 8), dtype=int)
    current_row, current_col = random.randint(0, 7), random.randint(0, 7)
    board[current_row, current_col] = 1
    counter = 2

    while True:
        valid_moves = []
        for move_number in range(8):
            next_row = current_row + vertical[move_number]
            next_col = current_col + horizontal[move_number]
            if is_valid_move(next_row, next_col, board):
                valid_moves.append((next_row, next_col))

        if not valid_moves: 
            break

        current_row, current_col = random.choice(valid_moves)
        board[current_row, current_col] = counter
        counter += 1

    return board, counter - 1

board, moves = random_knights_tour()
print("Final board:")
print(board)
print(f"The horse performed {moves} movements.")


Final board:
[[ 0  0  0  5  0  0  0  0]
 [ 0  0 15  0  0  4  0  0]
 [ 0  0  0  0  6  1 20  0]
 [ 0 14  0 16  3 18  0  0]
 [ 0  0 12  7  0 21  2 19]
 [13 28  0 26 17  8  0 22]
 [ 0 25 30 11  0 23 32  9]
 [29  0 27 24 31 10  0  0]]
The horse performed 32 movements.


In [ ]:
import matplotlib.pyplot as plt

def simulate_random_tours(num_tours=1000000):
    lengths = [0] * 65 
    for _ in range(num_tours):
        _, moves = random_knights_tour()
        lengths[moves] += 1

    return lengths

lengths = simulate_random_tours(1000000)

print("Tour Length:")
print("Movements | Frequency")
for i, freq in enumerate(lengths):
    if freq > 0:
        print(f"     {i:<8}  |  {freq}")

plt.bar(range(65), lengths)
plt.xlabel("Number of Moves")
plt.ylabel("Frequency")
plt.title("Tour Length Distribution")
plt.show()


In [ ]:
import time

def find_complete_tour():
    lengths = [0] * 65
    complete_tour_found = False
    attempts = 0
    start_time = time.time()

    while not complete_tour_found:
        _, moves = random_knights_tour()
        lengths[moves] += 1
        attempts += 1
        if moves == 64:
            complete_tour_found = True

    end_time = time.time()
    elapsed_time = end_time - start_time

    print("Tour Length Chart:")
    print("Movements | Frequency")
    for i, freq in enumerate(lengths):
        if freq > 0:
            print(f"     {i:<8}  |  {freq}")

    print(f"Full tour found after {attempts} attempts.")
    print(f"Total time: {elapsed_time:.2f} seconds.")

find_complete_tour()
