In [4]:
import numpy as np

# Initialize the chessboard
board = np.zeros((8, 8), dtype=int)

# Arrays for possible knight moves
horizontal = [2, 1, -1, -2, -2, -1, 1, 2]
vertical = [-1, -2, -2, -1, 1, 2, 2, 1]

# Starting position of the knight
start_row, start_col = 0, 0
current_row, current_column = start_row, start_col
board[current_row, current_column] = 1
counter = 2

# Function to check if a move is valid
def is_valid_move(row, col):
    return 0 <= row < 8 and 0 <= col < 8 and board[row, col] == 0

# Perform the knight's tour
while True:
    moved = False
    for move_number in range(8):
        next_row = current_row + vertical[move_number]
        next_column = current_column + horizontal[move_number]

        if is_valid_move(next_row, next_column):
            current_row, current_column = next_row, next_column
            board[current_row, current_column] = counter
            counter += 1
            moved = True
            break
    if not moved:
        break

# Check if a complete tour occurred
if counter - 1 == 64:
    # Test if the knight can return to the starting square
    closed_tour = False
    for move_number in range(8):
        test_row = current_row + vertical[move_number]
        test_col = current_column + horizontal[move_number]
        if test_row == start_row and test_col == start_col:
            closed_tour = True
            break

    print("Complete tour achieved!")
    if closed_tour:
        print("The tour is closed!")
    else:
        print("The tour is NOT closed!")
else:
    print("A complete tour was not achieved.")

# Display the final board and number of moves
print("\nFinal board:")
print(board)
print(f"\nMoves performed: {counter - 1}")


A complete tour was not achieved.

Final board:
[[ 1 10 23 42  7  4 13 18]
 [24 41  8  3 12 17  6 15]
 [ 9  2 11 22  5 14 19 32]
 [ 0 25 40 35 20 31 16  0]
 [ 0 36 21  0 39  0 33 30]
 [26  0 38  0 34 29  0  0]
 [37  0  0 28  0  0  0  0]
 [ 0 27  0  0  0  0  0  0]]

Moves performed: 42
