In [11]:
import numpy as np

board = np.zeros(((8,8)), dtype=int)

horizontal = [2, 1, -1, -2, -2, -1, 1, 2]
vertical = [-1, -2, -2, -1, 1, 2, 2, 1]

current_row, current_column = 0, 0
board[current_row, current_column] = 1
counter = 2

def is_valid_move(row, col):
    return 0 <= row < 8 and 0 <= col < 8 and board[row, col] == 0

while True:
    moved = False
    for move_number in range(8):
        next_row = current_row + vertical[move_number]
        next_column = current_column + horizontal[move_number]

        if is_valid_move(next_row, next_column):
            current_row, current_column = next_row, next_column
            board[current_row, current_column] += counter
            counter += 1
            moved = True
            break
    if not moved:
        break

print(board)
print(counter - 1)

[[ 1 10 23 42  7  4 13 18]
 [24 41  8  3 12 17  6 15]
 [ 9  2 11 22  5 14 19 32]
 [ 0 25 40 35 20 31 16  0]
 [ 0 36 21  0 39  0 33 30]
 [26  0 38  0 34 29  0  0]
 [37  0  0 28  0  0  0  0]
 [ 0 27  0  0  0  0  0  0]]
42


In [18]:
import numpy as np

accessibility = np.array([
    [2, 3, 4, 4, 4, 4, 3, 2],
    [3, 4, 6, 6, 6, 6, 4, 3],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [4, 6, 8, 8, 8, 8, 6, 4],
    [3, 4, 6, 6, 6, 6, 4, 3],
    [2, 3, 4, 4, 4, 4, 3, 2],
])

horizontal = [2, 1, -1, -2, -2, -1, 1, 2]
vertical = [-1, -2, -2, -1, 1, 2, 2, 1]

def is_valid_move(row, col, board):
    return 0 <= row < 8 and 0 <= col < 8 and board[row, col] == 0

def update_accessibility(row, col, accessibility, board):
     for move_number in range(8):
        next_row = row + vertical[move_number]
        next_col = col + horizontal[move_number]
        if is_valid_move(next_row, next_col, board):
            accessibility[next_row, next_col] -= 1

def knights_tour(start_row, start_col):
    board = np.zeros((8, 8), dtype=int)
    access = accessibility.copy()
    current_row, current_col = start_row, start_col
    board[current_row, current_col] = 1
    counter = 2

    while counter <= 64:
        best_move = None
        min_access = float('inf')

        for move_number in range(8):
            next_row = current_row + vertical[move_number]
            next_col = current_col + horizontal[move_number]
            if is_valid_move(next_row, next_col, board):
                if access[next_row, next_col] < min_access:
                    min_access = access[next_row, next_col]
                    best_move = (next_row, next_col)
        if best_move is None:
            break

        current_row, current_col = best_move
        board[current_row, current_col] = counter
        counter += 1

        update_accessibility(current_row, current_col, access, board)

    return board, counter - 1

complete_tours = 0
for start_row in range(8):
    for start_col in range(8):
        board, moves = knights_tour(start_row, start_col)
        if moves == 64:
            complete_tours += 1
        print(f"Tour started at ({start_row}, {start_col}) finished with {moves} moves.")

print(f"Number of completed tours: {complete_tours}")                   

Tour started at (0, 0) finished with 64 moves.
Tour started at (0, 1) finished with 64 moves.
Tour started at (0, 2) finished with 64 moves.
Tour started at (0, 3) finished with 64 moves.
Tour started at (0, 4) finished with 64 moves.
Tour started at (0, 5) finished with 64 moves.
Tour started at (0, 6) finished with 64 moves.
Tour started at (0, 7) finished with 64 moves.
Tour started at (1, 0) finished with 64 moves.
Tour started at (1, 1) finished with 64 moves.
Tour started at (1, 2) finished with 64 moves.
Tour started at (1, 3) finished with 64 moves.
Tour started at (1, 4) finished with 64 moves.
Tour started at (1, 5) finished with 64 moves.
Tour started at (1, 6) finished with 64 moves.
Tour started at (1, 7) finished with 64 moves.
Tour started at (2, 0) finished with 64 moves.
Tour started at (2, 1) finished with 64 moves.
Tour started at (2, 2) finished with 64 moves.
Tour started at (2, 3) finished with 64 moves.
Tour started at (2, 4) finished with 64 moves.
Tour started 