In [5]:
import numpy as np

array1 = np.ones((2, 3))
array1

array([[1., 1., 1.],
       [1., 1., 1.]])

In [8]:
array2 = np.zeros((3, 3))
array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
array3 = np.full((2, 5), 7)
array3

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])