In [3]:
import numpy as np

array = np.arange(0, 4).reshape(2, 2)
array

array([[0, 1],
       [2, 3]])

In [4]:
array ** 3

array([[ 0,  1],
       [ 8, 27]])

In [5]:
array + 7

array([[ 7,  8],
       [ 9, 10]])

In [6]:
array * 2

array([[0, 2],
       [4, 6]])