In [5]:
import numpy as np

array = np.linspace(1, 6, 6)
array

array([1., 2., 3., 4., 5., 6.])

In [6]:
array.astype(int)

array([1, 2, 3, 4, 5, 6])

In [7]:
array.astype(float)

array([1., 2., 3., 4., 5., 6.])

In [8]:
array.astype(str)

array(['1.0', '2.0', '3.0', '4.0', '5.0', '6.0'], dtype='<U32')