In [6]:
import numpy as np

a = [[10, 8, 6, 4, 2, 0], [0, 2, 4, 6, 8, 10]]
b = np.array(a)
b

array([[10,  8,  6,  4,  2,  0],
       [ 0,  2,  4,  6,  8, 10]])

In [10]:
c = b.flatten()
c[1] = 10
print(c)
print(b)

[10 10  6  4  2  0  0  2  4  6  8 10]
[[10  8  6  4  2  0]
 [ 0  2  4  6  8 10]]


In [12]:
d = b.ravel()
d[1] = 10
print(d)
print(b)

[10 10  6  4  2  0  0  2  4  6  8 10]
[[10 10  6  4  2  0]
 [ 0  2  4  6  8 10]]
