In [7]:
import numpy as np

zeros = np.full((2, 2), 0)
ones = np.full((2, 2), 1)

In [17]:
chess_bottom = np.hstack((zeros, ones, zeros, ones, zeros, ones, zeros, ones))
chess_top = np.hstack((ones, zeros, ones, zeros, ones, zeros, ones, zeros))

In [21]:
chess = np.vstack((chess_top, chess_bottom, chess_top, chess_bottom, chess_top, chess_bottom, chess_top, chess_bottom))
print(chess)

[[1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [1 1 0 0 1 1 0 0 1 1 0 0 1 1 0 0]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]
 [0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1]]


In [23]:
row_top = np.tile([1, 0], 4)
row_bottom = np.tile([0, 1], 4)

chess = np.tile(np.vstack((row_top, row_bottom)), (4, 1))
print(chess)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]
