In [3]:
import numpy as np

array1 = np.array([[0, 2], [4, 6]])
array2 = np.array([[1, 3], [5, 7]])

In [14]:
# a) Use horizontal stacking to create array3 with array2 to the right of array1.

array3 = np.hstack((array1, array2))
print(array3)

[[0 2 1 3]
 [4 6 5 7]]


In [15]:
# b) Use vertical splitting to create array4 and array5, with array4 containing the top row of array3 and array5 containing the bottom row.

array4, array5 = np.vsplit(array3, 2)
print(array4)
print(array5)

[[0 2 1 3]]
[[4 6 5 7]]


In [18]:
# c) Sort both array4 and array5 and use horizontal stacking for both sorted arrays to create array6.

array4_sorted = np.sort(array4, axis=1)
array5_sorted = np.sort(array5, axis=1)
array6 = np.hstack((array4_sorted, array5_sorted))
print(array6)

[[0 1 2 3 4 5 6 7]]


In [20]:
# d) Use vertical stacking to create array7 stacking array6 and the product of array6 with 10.

array7 = np.vstack((array6, array6 * 10))
print(array7)

[[ 0  1  2  3  4  5  6  7]
 [ 0 10 20 30 40 50 60 70]]
