In [3]:
# If the arrays do not have the same number of dimensions, the smaller one is padded with extra dimensions on the left.
array_1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape (2, 3)
array_2 = np.array([10, 20, 30])            # Shape (3,)
result_1 = array_1 + array_2
result_1

array([[11, 22, 33],
       [14, 25, 36]])

In [5]:
# Dimension sizes must be equal or one of them must be 1 to allow transmission.
array_3 = np.array([[1], [2], [3]])  # Shape (3, 1)
array_4 = np.array([10, 20, 30])    # Shape (3,)
try:
    result_2 = array_3 + array_4
except ValueError as e:
    result_2 = str(e)

result_2

array([[11, 21, 31],
       [12, 22, 32],
       [13, 23, 33]])

In [6]:
# Otherwise, a dimension mismatch error occurs.
array_5 = np.array([1, 2, 3])    # Shape (3,)
array_6 = np.array([[10], [20]]) # Shape (2, 1)
result_3 = array_5 + array_6

result_3

array([[11, 12, 13],
       [21, 22, 23]])