In [2]:
import numpy as np

array1 = np.array([[0, 2], [4, 6]])
array2 = np.array([[1, 3], [5, 7]])

In [3]:
#A

array3 = np.concatenate((array1, array2))
print(array3)

[[0 2]
 [4 6]
 [1 3]
 [5 7]]


In [4]:
array4, array5 = np.vsplit(array3, 2)
print(array4)
print(array5)

[[0 2]
 [4 6]]
[[1 3]
 [5 7]]


In [5]:
#C

array4_sorted = np.sort(array4, axis=1)
array5_sorted = np.sort(array5, axis=1)
array6 = np.concatenate((array4_sorted, array5_sorted))
print(array6)

[[0 2]
 [4 6]
 [1 3]
 [5 7]]


In [6]:
#D

array7 = np.concatenate((array6, array6 * 10))
print(array7)

[[ 0  2]
 [ 4  6]
 [ 1  3]
 [ 5  7]
 [ 0 20]
 [40 60]
 [10 30]
 [50 70]]
