In [2]:
import numpy as np

array = np.arange(1, 16).reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [4]:
array[1]

array([ 6,  7,  8,  9, 10])

In [9]:
array[:,3]

array([ 4,  9, 14])

In [12]:
array[:, [0, 1, 2]]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [13]:
array[0, 3]

4

In [15]:
array[0:2, [0, 2, 4]]

array([[ 1,  3,  5],
       [ 6,  8, 10]])